import assert from "node:assert/strict";
const base = process.argv[2] ?? "http://127.0.0.1:3000";
if (!/^http:\/\/(?:127\.0\.0\.1|localhost):\d+$/.test(base)) throw new Error("Use a loopback demo URL.");
async function call(path, method = "GET", body, expected = 200) {
  const response = await fetch(base + path, { method, headers: { "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  assert.equal(response.status, expected, `${method} ${path}`);
  return response.json();
}
const home = await fetch(base);
assert.equal(home.status, 200);
assert.match(await home.text(), /Sample inbox/);
await call("/api/settings/erase", "POST");
const inbox = await call("/api/inbox");
assert.equal(inbox.live, false);
assert.equal(inbox.messages.length, 7);
await call("/api/analyse", "POST", { message: "A pasted message is not accepted" }, 400);
const { analysis } = await call("/api/analyse", "POST", { inboxMessageId: "sample-workshop" });
const task = analysis.actions.find(a => a.type === "create_task");
assert.ok(task);
const path = `/api/actions/${task.id}`;
await call(path + "/execute", "POST", undefined, 403);
await call(path + "/approve", "POST");
const edited = await call(path, "PATCH", { type: task.type, payload: { ...task.payload, title: "Prepare synthetic agenda" } });
assert.equal(edited.action.status, "PROPOSED");
assert.equal(edited.action.approval, null);
await call(path + "/execute", "POST", undefined, 403);
await call(path + "/approve", "POST");
const done = await call(path + "/execute", "POST");
assert.equal(done.action.status, "EXECUTED");
assert.equal(done.action.execution.simulated, true);
await call(path + "/execute", "POST", undefined, 403);
const activity = await call("/api/activity");
assert.equal(activity.events.filter(e => e.type === "ACTION_EXECUTED").length, 1);
const injection = await call("/api/analyse", "POST", { inboxMessageId: "sample-injection" });
assert.equal(injection.analysis.suspectedInjection, true);
for (const action of injection.analysis.actions) assert.equal(action.approval, null);
assert.equal((await fetch(base + "/api/google/connect")).status, 404);
await call("/api/settings/erase", "POST");
assert.deepEqual((await call("/api/mode")).storage, { messages: 0, actions: 0, auditEvents: 0 });
console.log("HTTP smoke test passed: rendering, seven samples, validation, approval, editing, simulated execution, replay refusal, injection warning, activity, absent Google route and reset.");
